### ISSUE TITLE
Point sending form loses comment field after error

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-nonfree#103]
On http://www.dreamwidth.org/shop/transferpoints 

/shop/transferpoints.tt.buying.note goes away if you try to send points to an account that does not exist. 

Steps: 

In /shop/transferpoints.tt.buying.for put something bogus
Hit .tt.button.transfer 

Error: You can only buy points for an active account.

Note field goes away.

**Comment by kareila** [comment]
I moved this to dreamwidth/dw-free#1627 since the relevant page is not in dw-nonfree.
