### ISSUE TITLE
Hostname change requested for qdb.dreamwidth.net

### ISSUE THREAD

**Issue by Sophira** [dreamwidth/dw-nonfree#104]
Hi,

I've had to do a server move, and the QDB has had to move with it, so the name qdb.dreamwidth.net will need to be updated to point to the new IP.

Would it be possible to make **qdb.dreamwidth.net** point to **70.85.16.85**, please? (Currently it would be pointing at **74.52.15.98**. I notice that the DNS is actually pointing to CloudFlare, but I assume that it passes through, so I'm guessing that the config should be changed there.)

I hope this is the right place to put this issue. I had put this as an issue in dw-ops initially as I figured that was more appropriate, but it wasn't seen, so I'm putting it here. :)

Thank you!

**Comment by Sophira** [comment]
Hi,

Should I be putting this in dw-free's issue list instead? It doesn't seem right to put it there because it's really an ops thing instead of something that concerns the open source code, but I can put it there if need be.

**Comment by kareila** [comment]
You're probably better off just sending email to Mark, since he's the only one who can update the DNS.

**Comment by zorkian** [comment]
I read these, it's on my todo list but hasn't been a high priority thing

**Comment by zorkian** [comment]
Updated to 70.85.16.85, but it doesn't seem to work

**Comment by Sophira** [comment]
Fixed, thanks. :)
