### ISSUE TITLE
qdb.dreamwidth.net IP address change

### ISSUE THREAD

**Issue by Sophira** [dreamwidth/dw-nonfree#122]
Hi,

The server which the Dreamwidth QDB is located on needs to change IP addresses because of a network reorganisation taking place by my provider, and as such I need to ask for a change in the CloudFlare settings for **qdb.dreamwidth.net** - sorry about that!

The new IP address is **72.14.185.85**. Currently the server is responding on both the old IP and this new one, so there shouldn't be any downtime when the change is made. I've made a simple script at http://qdb.dreamwidth.net/interfaceip.cgi which tells you which IP the response is being sent from (and it uses `Cache-Control: private, max-age=0, no-cache, no-store`, so the response won't be cached), so you can use that to know if the change worked! I'll remove that script after this is resolved.

Thank you!

**Comment by alierak** [comment]
Okay, updated and tested.

**Comment by Sophira** [comment]
Thanks! And I'm so sorry - I just realised I disabled the old IP about a week ago and totally forgot about the QDB! Thank you for making the change. <3
